+ первый коммит по ТЗ спринта 14
Triapkin/java-shareit pull request #1
Opened 2024-09-10 19:03 UTC by Triapkin

2024-09-11 18:33 UTC, z8q requested changes

2024-09-11 18:33 UTC, z8q commented on src/main/java/ru/practicum/shareit/exception/GlobalExceptionHandler.java
> +        return errors;
Можно попробовать немного оптимизировать
```JAVA
public Map<String, String> handleValidationExceptions(MethodArgumentNotValidException ex) {
    return ex.getBindingResult().getFieldErrors().stream()
            .collect(Collectors.toMap(
                FieldError::getField, 
                FieldError::getDefaultMessage, 
                (existing, replacement) -> existing
            ));
}
```
В последней строке еще можно управлять данными для существующих ключей в мапе,
либо оставлять существующий, либо заменять

2024-09-11 18:33 UTC, z8q commented on src/main/java/ru/practicum/shareit/exception/GlobalExceptionHandler.java
> +        return error;
тут можно посмотреть
return Map.of(...)
или
return Collections.singletonMap("error", ex.getMessage());

2024-09-11 18:33 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserServiceImpl userServiceImpl;
Здесь стоит указать интерфейс вместо реализации
Так уменьшим связность между объектами
И в случае, если реализация будет меняться (будет например другой класс имплементирующий интерфейс UserService), в этом классе ничего менять не придется

2024-09-11 18:33 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = users.get(userId);
Можно попробовать сократить количество обращений к мапе
мы вызываем getUserById(id) и users.get(userId)

Нам нужна логика
```JAVA
        User user = users.get(id);
        if (user == null) {
            throw new NotFoundException("Пользователь не найден");
        }
```
для метода updateUser и getUserById
Мы можем выделить ее в отдельный приватный метод, который бы возвращал User после проверки
и далее вызывать этот новый метод в updateUser и getUserById

2024-09-11 18:33 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        int userId = Math.toIntExact(id);
Можно рассмотреть использование long в качестве id, чтобы не делать преобразования

2024-09-12 16:08 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/exception/GlobalExceptionHandler.java
> +        return errors;
исправил

2024-09-12 16:08 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/exception/GlobalExceptionHandler.java
> +        return error;
исправил

2024-09-12 16:09 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserServiceImpl userServiceImpl;
исправил

2024-09-12 16:20 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = users.get(userId);
вынес поиск по мапе в отдельный метод, в updateUser стал использовать метод поиска getUserById, теперь поиск в мапе используется только в одном места

2024-09-12 16:22 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        int userId = Math.toIntExact(id);
непонятно зачем тут вообще это использовал, у нас и так прилетает userId - int :(

2024-09-13 14:19 UTC, z8q approved these changes

2024-10-04 09:36 UTC, merged