Add bookings
Triapkin/java-shareit pull request #2
Opened 2024-10-07 07:17 UTC by Triapkin

2024-10-07 19:48 UTC, z8q requested changes

2024-10-07 19:48 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                              @RequestHeader("X-Sharer-User-Id") @NotNull int bookerId,
Если перейти в аннотацию RequestHeader, в ней есть параметр required, который в дефолтном значении равен true
Можно не использовать NotNull,
еще bookerId является примитивом, то есть не может быть null, NotNull обычно используется для объектных типов

2024-10-07 19:48 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                        @RequestHeader("X-Sharer-User-Id") int userId) {
Попробуй создать в GlobalExceptionHandler два хэндлера вместо handleIllegalArgumentException(IllegalArgumentException ex)
```JAVA
    @ExceptionHandler(MissingRequestHeaderException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public Map<String, String> handleMissingRequestHeaderException(MissingRequestHeaderException exception) {
        return Map.of("error", exception.getMessage());
    }

    @ExceptionHandler(MethodArgumentTypeMismatchException.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public Map<String, String> handleMethodArgumentTypeMismatchException(MethodArgumentTypeMismatchException exception) {
        return Map.of("error", exception.getMessage());
    }
```

И потом сделать такой вызов
```
curl --request POST \
  --url http://localhost:8080/bookings \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: ' \
  --data '{
	"itemId": 1,
	"start": "2024-08-19T23:44:10",
	"end": "2024-08-19T23:44:20"
}'
```
хэдер X-Sharer-User-Id есть, но значение не указано

Если в методе BookingController. addBookingRequest для аргумента userId оставим примитивный тип int, придет такое сообщение
```
{
 "error": "Failed to convert value of type 'java.lang.String' to required type 'int'; nested exception is java.lang.NumberFormatException: For input string: \"\""
}
```
Если исправим тип на обертку -  Integer userId, на такой же запрос будем получать более понятное сообщение
```
{
 "error": "Required request header 'X-Sharer-User-Id' for method parameter type Integer is present but converted to null"
}
```

Предложил поставить два хендлера, потому что в зависимости от типа хедера будут разные исключения

2024-10-07 19:48 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingService bookingService;
Можно сделать поле private, для ограничения видимости
и final для возможности задать значение только один раз

Тогда аннотацию AllArgsConstructor можно будет заменить на RequiredArgsConstructor,
ломбок создаст конструктор для final, non-initialized полей, то есть для bookingService

2024-10-07 19:48 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                              @RequestParam @NotNull Boolean approved) {
В RequestParam тоже есть параметр required, который равен true

2024-10-07 19:48 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ValidationException("Поля не могут быть пустыми");
Если в запросе не указать  start
```
curl --request POST \
  --url http://localhost:8080/bookings \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 3' \
  --data '{
	"itemId": 1,
	"end": "2024-08-19T23:44:20"
}'
```

то получим ошибку с кодом 500
```JSON
{
	"timestamp": "2024-10-07T19:13:59.231+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/bookings"
}
```

Можно попробовать обработать в GlobalExceptionHandler

2024-10-07 19:48 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ValidationException("Поля не могут быть пустыми");
Если использовать валидационные аннотации над полями BookingDto,
то можно было бы сделать что-то такое
```JAVA
    @NotNull(message = "start can't be null")
    private LocalDateTime start;
    @NotNull(message = "end can't be null")
    private LocalDateTime end;
```

2024-10-07 19:48 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
На дипломе будут рекомендовать не использовать Data с сущностями, 
статьи про это:
https://thorben-janssen.com/lombok-hibernate-how-to-avoid-common-pitfalls/
https://habr.com/ru/companies/haulmont/articles/564682/
https://jpa-buddy.com/blog/hopefully-the-final-article-about-equals-and-hashcode-for-jpa-entities-with-db-generated-ids/

Один из примеров возможных проблем
Data содержит в себе toString

У нас например есть сущность с каким-нибудь полем OneToMany Set<Items> items,
У OneToMany по умолчанию параметр fetch == FetchType.LAZY
Это значит, что, если мы запросим из базы саму сущность, items не будут подгружены,
но у нас есть созданный ломбоком toString(), и если мы где-то его вызовем, то могут возникать дополнительные обращения к базе
Если такие обращения будут при уже закрытой сессии хибернейта, то можем получить LazyInitializationException

2024-10-08 17:09 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                              @RequestHeader("X-Sharer-User-Id") @NotNull int bookerId,
спасибо, исправил

2024-10-08 17:10 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    BookingService bookingService;
исправил

2024-10-08 17:10 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                              @RequestParam @NotNull Boolean approved) {
исправил

2024-10-08 17:13 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ValidationException("Поля не могут быть пустыми");
спасибо, добавил аннотации к дто

2024-10-08 17:17 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                        @RequestHeader("X-Sharer-User-Id") int userId) {
спасибо, крутой комментарий, добавил в GlobalExceptionHandler

2024-10-08 17:33 UTC, Triapkin commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Data
исправил

2024-10-08 19:02 UTC, z8q approved these changes

2024-10-08 19:02 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                              @RequestHeader("X-Sharer-User-Id") int bookerId,
Хотел в прошлом комментарии сказать, что лучше использовать классы обертки вместо примитивов,
то есть Integer вместо int

2024-10-08 20:30 UTC, merged